baseURL = 'https://JoseMariaMicoli.github.io/'
title = 'Ghost-Hydra Intelligence'
theme = 'terminal'

[params]
  themeColor = "green"
  contentTypeName = "posts"
  author = "J.M. Micoli"
  logoText = "GHOST-HYDRA INTELLIGENCE" 
  # Favicon path relative to the static folder
  favicon = "images/favicon.ico"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  series = "/series/:slug/"

[languages]
  [languages.en]
    languageCode = "en-us"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Manifesto"
        url = "/posts/manifesto"
        weight = 10
      [[languages.en.menu.main]]
        name = "Cyber Attack Anatomy"
        url = "/series/anatomy-of-an-attack"
        weight = 20
      [[languages.en.menu.main]]
        name = "RED-TEAM Professional Suite"
        url = "/categories/pro-suite/"
        weight = 30
      [[languages.en.menu.main]]
        name = "ExploitDevLog"
        url = "/categories/devlog/"
        weight = 40
      [[languages.en.menu.main]]
        name = "Intel Feed"
        url = "/posts"
        weight = 50
      [[languages.en.menu.main]]
        name = "Legal"
        url = "/license"
        weight = 60
      [[languages.en.menu.main]]
        name = "WHOAMI"
        url = "/whoami/"
        weight = 5
