baseURL = 'https://JoseMariaMicoli.github.io/'
title = 'Ghost-Hydra Intelligence'
theme = 'terminal'

[params]
  themeColor = "green"
  contentTypeName = "posts"
  author = "J.M. Micoli"
  codename = "Xoce"
  # This puts the name at the top of every page
  logoText = "GHOST-HYDRA INTELLIGENCE" 

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[languages]
  [languages.en]
    languageCode = "en-us"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Manifesto"
        url = "/posts/manifesto"
        weight = 1
      [[languages.en.menu.main]]
        name = "Attack Anatomy"
        url = "/series/anatomy-of-an-attack"
        weight = 2
      [[languages.en.menu.main]]
        name = "Intel Feed"
        url = "/posts"
        weight = 3
      [[languages.en.menu.main]]
        name = "Legal"
        url = "/license"
        weight = 4