baseURL = 'https://JoseMariaMicoli.github.io/'
title = 'Ghost-Hydra Intelligence'
theme = 'terminal'

[params]
  themeColor = "green"
  # This ensures the home page shows your latest posts
  contentTypeName = "posts" 
  author = "J.M. Micoli"
  logoText = "GHOST-HYDRA INTELLIGENCE" 
  favicon = "favicon.ico"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  # This makes the URL for your reports cleaner
  htb-reports = "/htb-reports/:filename/"

[languages]
  [languages.en]
    languageCode = "en-us"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "WHOAMI"
        url = "/whoami"
        weight = 5

      [[languages.en.menu.main]]
        name = "Manifesto"
        url = "/posts/manifesto"
        weight = 10

      [[languages.en.menu.main]]
        name = "HTB Audit Log"
        url = "/htb-reports"
        weight = 15

      [[languages.en.menu.main]]
        name = "Cyber Attack Anatomy"
        url = "/attack-anatomy"
        weight = 20

      [[languages.en.menu.main]]
        name = "RED-TEAM Pro Suite"
        url = "/pro-suite"
        weight = 30

      [[languages.en.menu.main]]
        name = "Intel Feed"
        url = "/posts"
        weight = 50